services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: textura-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: textura
    volumes:
      - mongodb_data:/data/db
    networks:
      - textura-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: textura-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/textura?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-here
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/images:/app/images
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - textura-network
    command: ["npm", "run", "setup-and-run"]

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: textura-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/.env:/app/.env
    depends_on:
      - backend
    networks:
      - textura-network

volumes:
  mongodb_data:

networks:
  textura-network:
    driver: bridge
